apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  labels:
    app: kong
spec:
  type: LoadBalancer # Gunakan LoadBalancer untuk akses eksternal di cloud, atau NodePort/ClusterIP
  selector:
    app: kong
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  labels:
    app: kong
spec:
  type: ClusterIP # Akses internal saja (Admin API tidak terekspos langsung ke publik)
  selector:
    app: kong
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http-admin # Penting: Prometheus akan scrape dari port ini
  - port: 8444
    targetPort: 8444
    protocol: TCP
    name: https-admin
