apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
data:
  kong-official-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": 7424,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        # Tempelkan seluruh JSON dashboard Grafana di sini
        # Anda bisa mengunduhnya dari https://grafana.com/grafana/dashboards/7424-kong-official-dashboard/
        # Pastikan formatnya benar setelah ditempel
      ],
      "schemaVersion": 26,
      "style": "dark",
      "tags": [
        "kong"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": true,
              "text": "All",
              "value": "$__all"
            },
            "datasource": "Prometheus",
            "definition": "label_values(kong_nginx_http_requests_total_sum, service)",
            "description": null,
            "hide": 0,
            "includeAll": true,
            "label": "Service",
            "multi": true,
            "name": "service",
            "options": [],
            "query": "label_values(kong_nginx_http_requests_total_sum, service)",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tags": [],
            "type": "query",
            "useAllValue": false
          }
        ]
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "",
      "title": "Kong Official Dashboard",
      "uid": "7424-kong-official-dashboard",
      "version": 1
    }
