apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-config
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090 # Ini adalah nama Service Prometheus di Kubernetes
        isDefault: true
        access: proxy
