apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # Atur interval scrape
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kong'
        metrics_path: '/metrics' # Default path untuk plugin Prometheus Kong
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: kong-admin;http-admin # Pastikan ini sesuai dengan nama service dan port Admin Kong Anda
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
